### ISSUE TITLE
how to use d3-bootstrap for popover in d3.js v4

### ISSUE THREAD

**Issue by s7e-20** [sebt3/d3-bootstrap#1]

**Comment by sebt3** [comment]
As describe in the documentation : https://sebt3.github.io/d3-bootstrap/documentation.html
1st) have the js libraries loaded :     <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="js/d3-bootstrap.js"></script>
2nd) use this :
&lt;a href="#" data-toggle="popover" data-placement="right" title="Popover Header" data-content="Some content inside the popover">Toggle popover there -></a>

Exactly as you would do with regular bootstrap. But unlike with regular bootstrap, you dont have to activate it since my implementation have very small performance impact

**Comment by s7e-20** [comment]
Thank you for your fast advice.
Is it possible to add links and a lot of other stuff in content of the popover?

**Comment by sebt3** [comment]
Never tested. But it probably work as "data-content" can be html.

**Comment by sebt3** [comment]
As per commit 9fdccb6, the documentation have been updated to demo that this works
